### ISSUE TITLE
Error: Message too long

### ISSUE THREAD

**Issue by ADV-MMT** [mikeokner/posix-mq#4]
I am getting an error that my mqueue message is too long. Seems like my msgsize parameter isn't working in mq.open() 

Here's the code that I'm using: 

```
const PosixMQ = require('posix-mq');
var mq = new PosixMQ();

app.post('/', function(req, res){
	mq.open({
		name: '/testing',
		create: true,
		mode: 0777,
		maxmsgs: 10,
		msgsize: 256 
	});
       
        var str = JSON.stringify(req.body.data);

	console.log("Max size is: " + mq.msgsize);
        //Prints '8' regardless of value of msgsize above

	console.log("Writing " +  str + " to the queue..");
        // Prints 'Writing helloworld to the queue' 

	mq.push(str); //Error: Message too long
       
	
	mq.close();
});
```

Any help is appreciated. 

Node version: 10.15.4

**Comment by mikeokner** [comment]
Hi Max,

I suspect it's one of two issues:

More likely the queue already exists on the system and was created with a msgsize of 8 previously, so `mq.open` is returning that existing queue rather than creating a new one. You could try calling `mq.unlink()` to remove the queue from the system and then try creating it again with the larger msgsize. If you don't want a queue to live past the lifetime of your script, you should make a habit of calling `mq.unlink()` before `mq.close()`. [Example here](https://github.com/mikeokner/posix-mq/blob/master/test.js#L29).

Less likely that it could also be that you are bumping into a system limit or unusual configuration on the host. You can check the system-wide settings by viewing the contents of the following two files:

```console
$ cat /proc/sys/fs/mqueue/msgsize_default 
8192
$ cat /proc/sys/fs/mqueue/msgsize_max 
8192
```

If you omit the `msgsize` parameter from the constructor options (and the queue doesn't already exist), then the new queue will use the value from that first file as the `msgsize` which by default in Linux should be 8192.

Hope that helps!

**Comment by ADV-MMT** [comment]
Thanks for taking the time to give a detailed response! Your assumption was correct, the problem was happening because of the queue already existing on the system.
